language: python

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: pypy3
          env: TOXENV=pypy3

# Adapted from https://github.com/biopython/biopython/commit/4b4902ffeb4da519c20a7b5c0996bfde681bee1f
before_install:
  - cd $HOME
  - mkdir bin
  - export PATH=$HOME/bin:$PATH
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && tar -jxf pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3.3 ~/bin/python && echo 'Setting up pip...' && pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy -m ensurepip && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pip3.3 ~/bin/pip ; fi"
  - cd $TRAVIS_BUILD_DIR

install:
  - "pip install tox"
  - "pip install codecov"
  - "pip install sphinx"

script: "tox -- -rs"

after_success:
  - codecov
  - chmod a+x ./.travis/deploy_docs.sh
  - ./.travis/deploy_docs.sh
